version: '3.1'

networks:
  dbnetwork:
    driver: bridge

  appnetwork:
    driver: bridge

services:

  mongo:
    image: mongo
    restart: always
    container_name: mongo_container
    environment:
       MONGO_INITDB_ROOT_USERNAME: root
       MONGO_INITDB_ROOT_PASSWORD: example

  mongo-express:
    image: mongo-express
    restart: always
    container_name: mongoex_container
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/

  appication1:
    depends_on:
       - mongo-express
    image: app_prd:1.0
    restart: always
    container_name: app_container
    ports:
      - 80:80
    stdin_open: true
    tty: true