pipeline {
         agent {
        label 'master'
    }
    node("master") {
        
        stage('Clone repository') {

    
            checkout scm


        }

        stage('Echo') {
            echo "Repositório clonado"
        }
    }
}