pipeline {
    agent {
        label 'master'
    }

    stages{
        stage('Clone repository') {
            checkout scm
        }

        stage('Echo') {
            echo "Repositório clonado"
        }
    }

}
